# Generated by Django 3.1.7 on 2021-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=20)),
                ('Slug', models.CharField(max_length=150)),
                ('Timestamp', models.DateTimeField(blank=True)),
                ('Content', models.TextField()),
            ],
        ),
    ]
