# Generated by Django 3.1.7 on 2021-04-06 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_comment',
            fields=[
                ('Serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.TextField()),
                ('Time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogging.blog_comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
